name: '&l&8Charcoal Elytra'
recipe: #You can change the material used.
  #FULL BLOCK NAME LIST: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  #You may have to restart the server to update ingredients.
  ingredients_A: 'DRAGON_BREATH'
  ingredients_B: 'NETHERITE_INGOT'
  ingredients_C: 'ELYTRA'
  ingredients_D: 'NETHER_STAR'
  ingredients_E: 'CLOCK'
ingame_editor: #represents the matrix for the crafting bench. The index is the slot of the crafting bench and the item that is in it.
  enable: false
  index_0:
  index_1:
  index_2:
  index_3:
  index_4:
  index_5:
  index_6:
  index_7:
  index_8:
remove_recipe: false
speed: 2.5
cooldown: 10 #seconds
messages:
  launch: "&4&lYou are taking off! &r&l&8&nPress Shift to boost yourself!"
  cooldown: "&8&lYou cannot boost yet"
texture-link: "https://www.dropbox.com/sh/gl3vifm2pal1hxr/AAA-U-1deNQrOn2HLWaosgqVa?dl=1"
permissions:
  BetterElytra.staff #Used for the give elytra command