name: Betterelytra
version: 1.0
main: me.minercoffee.betterelytra.Main
api-version: 1.19
load: STARTUP
authors: [ MinerCoffee ]
description: Better elytra with custom recipe, custom name, fall resistance, customize config
website: https://discord.gg/HHFSdmZZW2
commands:
  updater:
   usage: /<command>
   description: checks for an update in-game.
  elytra:
   usage: /<command> give
   description: gives the elytra to the player.
  bereload:
    usage:  /<command>
    description: reloads the config.yml.
  bcraft:
    usage:  /<command>
    description: opens the crafting bench
permissions:
  BetterElytra.staff:
    description: used for staff/admin commands.
    default: false